GET http://localhost:3003/ping
###

POST http://localhost:3003/create-table-users
###

POST http://localhost:3003/create-table-products
###

POST http://localhost:3003/create-table-purchases-products
###

GET http://localhost:3003/users
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "user04",
    "name": "Danila",
    "email": "nila@email.com",
    "password": "45631987el"
}
###

DELETE http://localhost:3003/users/user04
###

PUT http://localhost:3003/users/user02
Content-Type: application/json

{
    "id": "a003",
    "ownerName": "Juliano",
    "balance": 1000000000,
    "type": "Ouro"
}
###

GET http://localhost:3003/products
###

GET http://localhost:3003/products/dell
###

POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "p007",
    "name": "Impressora Multfuncional Lexmark MX511de",
    "price": 5565.81,
    "description": "Impressara com multiplas funções.",
    "imageUrl": "https://encurtador.com.br/K2hjy"
}
###

PUT http://localhost:3003/products/p001
Content-Type: application/json

{
    "imageUrl": "https://encurtador.com.br/9DFV7"
}
###

DELETE http://localhost:3003/products/p007
###

GET http://localhost:3003/purchases
###

POST http://localhost:3003/purchases
Content-Type: application/json

{
    "id": "buy003",
    "buyer": "user02",
    "total_price": 3220.78,
    "creadet_at": "2024-08-16 10:54:01"
}
###

GET http://localhost:3003/purchases/buy001
###

GET http://localhost:3003/purchases-products
###

POST http://localhost:3003/purchases-products
Content-Type: application/json

{
    "purchase_id": "buy003",
    "product_id": "p002",
    "quantity": 1
}
###